// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace HopeLingerieSite.Controllers.Backoffice {
    public partial class BackOfficeController {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public BackOfficeController() { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected BackOfficeController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result) {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }


        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public BackOfficeController Actions { get { return MVC.BackOffice; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "BackOffice";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass {
            public readonly string ContactGridView = "ContactGridView";
            public readonly string Contacts = "Contacts";
            public readonly string ProductGridView = "ProductGridView";
            public readonly string Products = "Products";
            public readonly string CustomerGridView = "CustomerGridView";
            public readonly string Customers = "Customers";
            public readonly string FranchiseGridView = "FranchiseGridView";
            public readonly string Franchises = "Franchises";
            public readonly string Index = "Index";
            public readonly string OrderGridView = "OrderGridView";
            public readonly string Orders = "Orders";
            public readonly string NewsLetterGridView = "NewsLetterGridView";
            public readonly string NewsLetters = "NewsLetters";
            public readonly string CategoryGridView = "CategoryGridView";
            public readonly string Categories = "Categories";
        }


        static readonly ViewNames s_views = new ViewNames();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewNames Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewNames {
            public readonly string CategoryGridView = "~/Views/BackOffice/CategoryGridView.ascx";
            public readonly string CategoryList = "~/Views/BackOffice/CategoryList.aspx";
            public readonly string CategoryUpdate = "~/Views/BackOffice/CategoryUpdate.aspx";
            public readonly string ColorList = "~/Views/BackOffice/ColorList.aspx";
            public readonly string ColorUpdate = "~/Views/BackOffice/ColorUpdate.aspx";
            public readonly string ContactGridview = "~/Views/BackOffice/ContactGridview.ascx";
            public readonly string ContactList = "~/Views/BackOffice/ContactList.aspx";
            public readonly string CustomerGridView = "~/Views/BackOffice/CustomerGridView.ascx";
            public readonly string CustomerList = "~/Views/BackOffice/CustomerList.aspx";
            public readonly string CustomerUpdate = "~/Views/BackOffice/CustomerUpdate.aspx";
            public readonly string FranchiseGridView = "~/Views/BackOffice/FranchiseGridView.ascx";
            public readonly string FranchiseList = "~/Views/BackOffice/FranchiseList.aspx";
            public readonly string NewsLetterGridView = "~/Views/BackOffice/NewsLetterGridView.ascx";
            public readonly string NewsLetterList = "~/Views/BackOffice/NewsLetterList.aspx";
            public readonly string OrderGridView = "~/Views/BackOffice/OrderGridView.ascx";
            public readonly string OrderList = "~/Views/BackOffice/OrderList.aspx";
            public readonly string OrderUpdate = "~/Views/BackOffice/OrderUpdate.aspx";
            public readonly string ProductGridView = "~/Views/BackOffice/ProductGridView.ascx";
            public readonly string ProductList = "~/Views/BackOffice/ProductList.aspx";
            public readonly string ProductUpdate = "~/Views/BackOffice/ProductUpdate.aspx";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public class T4MVC_BackOfficeController: HopeLingerieSite.Controllers.Backoffice.BackOfficeController {
        public T4MVC_BackOfficeController() : base(Dummy.Instance) { }

        public override System.Web.Mvc.ActionResult ContactGridView() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.ContactGridView);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Contacts() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Contacts);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult ProductGridView() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.ProductGridView);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Products() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Products);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult CustomerGridView() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.CustomerGridView);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Customers() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Customers);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult FranchiseGridView() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.FranchiseGridView);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Franchises() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Franchises);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Index() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Index);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult OrderGridView() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.OrderGridView);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Orders() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Orders);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult NewsLetterGridView() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.NewsLetterGridView);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult NewsLetters() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.NewsLetters);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult CategoryGridView() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.CategoryGridView);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Categories() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Categories);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591
