// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace HopeLingerieSite.Controllers {
    public partial class CatalogoController {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public CatalogoController() { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected CatalogoController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result) {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult ProductDetail() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.ProductDetail);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public CatalogoController Actions { get { return MVC.Catalogo; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Catalogo";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass {
            public readonly string Index = "Index";
            public readonly string Novedades = "Novedades";
            public readonly string Liquidacion = "Liquidacion";
            public readonly string Bragas = "Bragas";
            public readonly string Fajas = "Fajas";
            public readonly string Outlet = "Outlet";
            public readonly string Sutienes = "Sutienes";
            public readonly string Mallas = "Mallas";
            public readonly string Salon = "Salon";
            public readonly string ProductDetail = "ProductDetail";
        }


        static readonly ViewNames s_views = new ViewNames();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewNames Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewNames {
            public readonly string Categories = "~/Views/Catalogo/Categories.aspx";
            public readonly string Landing = "~/Views/Catalogo/Landing.aspx";
            public readonly string NoCategories = "~/Views/Catalogo/NoCategories.aspx";
            public readonly string NoCategoriesDetail = "~/Views/Catalogo/NoCategoriesDetail.aspx";
            public readonly string Product = "~/Views/Catalogo/Product.ascx";
            public readonly string ProductDetail = "~/Views/Catalogo/ProductDetail.ascx";
            public readonly string Products = "~/Views/Catalogo/Products.ascx";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public class T4MVC_CatalogoController: HopeLingerieSite.Controllers.CatalogoController {
        public T4MVC_CatalogoController() : base(Dummy.Instance) { }

        public override System.Web.Mvc.ActionResult Index() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Index);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Novedades() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Novedades);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Liquidacion() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Liquidacion);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Bragas() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Bragas);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Fajas() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Fajas);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Outlet() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Outlet);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Sutienes() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Sutienes);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Mallas() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Mallas);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Salon() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Salon);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult ProductDetail(object Id) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.ProductDetail);
            callInfo.RouteValueDictionary.Add("Id", Id);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591
