// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace HopeLingerieSite.Controllers.ShopingCart {
    public partial class ShoppingCartController {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected ShoppingCartController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result) {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult DeleteOrderDetail() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.DeleteOrderDetail);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult CalculateCoupon() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.CalculateCoupon);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult LogOn() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.LogOn);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ShoppingCartController Actions { get { return MVC.ShoppingCart; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "ShoppingCart";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass {
            public readonly string Index = "Index";
            public readonly string DeleteOrderDetail = "DeleteOrderDetail";
            public readonly string CalculateCoupon = "CalculateCoupon";
            public readonly string Step1 = "Step1";
            public readonly string Step2 = "Step2";
            public readonly string Step3 = "Step3";
            public readonly string Step4 = "Step4";
            public readonly string StepEnd = "StepEnd";
            public readonly string LogOn = "LogOn";
        }


        static readonly ViewNames s_views = new ViewNames();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewNames Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewNames {
            public readonly string Order = "~/Views/ShoppingCart/Order.ascx";
            public readonly string OrderDetail = "~/Views/ShoppingCart/OrderDetail.ascx";
            public readonly string OrderDetailDisplay = "~/Views/ShoppingCart/OrderDetailDisplay.ascx";
            public readonly string OrderDisplay = "~/Views/ShoppingCart/OrderDisplay.ascx";
            public readonly string Step1 = "~/Views/ShoppingCart/Step1.aspx";
            public readonly string Step2 = "~/Views/ShoppingCart/Step2.aspx";
            public readonly string Step3 = "~/Views/ShoppingCart/Step3.aspx";
            public readonly string Step4 = "~/Views/ShoppingCart/Step4.aspx";
            public readonly string StepEnd = "~/Views/ShoppingCart/StepEnd.aspx";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public class T4MVC_ShoppingCartController: HopeLingerieSite.Controllers.ShopingCart.ShoppingCartController {
        public T4MVC_ShoppingCartController() : base(Dummy.Instance) { }

        public override System.Web.Mvc.ActionResult Index() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Index);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult DeleteOrderDetail(int id) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.DeleteOrderDetail);
            callInfo.RouteValueDictionary.Add("id", id);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult CalculateCoupon(string CouponCode) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.CalculateCoupon);
            callInfo.RouteValueDictionary.Add("CouponCode", CouponCode);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Step1() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Step1);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Step2() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Step2);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Step3() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Step3);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Step3(HopeLingerieServices.Model.Customer customer) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Step3);
            callInfo.RouteValueDictionary.Add("customer", customer);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Step4() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Step4);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult StepEnd() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.StepEnd);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult LogOn(System.Web.Mvc.FormCollection formCollection) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.LogOn);
            callInfo.RouteValueDictionary.Add("formCollection", formCollection);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591
